# © 2025-2026 Intel Corporation
# DO NOT edit this file, because it is generated automatically
# This is a basic example to demonstrate how to use wdt_common module
# It's an example to show how to access wdt register in python test, too

import dev_util
import simics
import conf
# Import stest module if using stest.expect_equal(val, expected_val) etc.
import stest
import wdt_common

def test_wdt():
    # Create an instance of the device to test
    devs = wdt_common.create_config()
    dev = devs[0]
    connected_dev = devs[1]

    # Access the pyobj class object attribute directly outside the class
    signal_raised_cnt = connected_dev.raised
    stest.expect_equal(signal_raised_cnt, 0)

    regs = dev_util.bank_regs(dev.bank.WatchdogRegisters)

    # Write/read a register of wdt
    written_val = 0xdeadbeef
    regs.WDOGLOAD.write(written_val)
    # Run 100 cycles/steps
    simics.SIM_continue(100)
    read_val = regs.WDOGLOAD.read()
    print(f'written_val: {written_val}')
    print(f'read_val: {read_val}')
    print('Test complete successfully!')


if __name__ == "__main__":
    test_wdt()
