# © 2025-2026 Intel Corporation
# DO NOT edit this file, because it is generated automatically

import simics
import stest
import pyobj

# Ignore 'spec-viol' or 'unimpl' logs, test modeled behavior firstly
stest.untrap_log('spec-viol')
stest.untrap_log('unimpl')

class FakePic(pyobj.ConfObject):
    """Fake interrupt controller"""
    
    class raised(pyobj.SimpleAttribute(0, 'i')): pass
    
    class signal(pyobj.Interface):
        def signal_raise(self):
            """Called when device raises interrupt"""
            # Access the pyobj class attribute using `.val` inside the pyobj class
            self._up.raised.val += 1
            
        def signal_lower(self):
            """Called when device lowers interrupt"""
            # Access the pyobj class attribute using `.val` inside the pyobj class
            self._up.raised.val -= 1

def create_config():
    # Create device
    dev = simics.pre_conf_object('dev', 'wdt')
    clk = simics.pre_conf_object('clk', 'clock')
    mem = simics.pre_conf_object('mem', 'memory-space')
    
    # 2. Configure attributes BEFORE SIM_add_configuration
    clk.freq_mhz = 100  # ⚠️ CRITICAL: Set BEFORE instantiation
    dev.queue = clk     # REQUIRED for time-dependent devices
    
    # 3. Configure memory mapping
    mem.map = []
    # Map bank to memory space [base_addr, bank_obj, func, offset, size]
    mem.map += [[0x0, dev.bank.WatchdogRegisters, 0, 0, 0x1000]]
    
    # Create fake PICs for output ports
    fake_pic_wdogint = simics.pre_conf_object('fake_pic_wdogint', 'FakePic')
    fake_pic_wdogres = simics.pre_conf_object('fake_pic_wdogres', 'FakePic')
    
    # Connect device output ports to fake PICs
    dev.wdogint = fake_pic_wdogint  # DML: connect wdogint { ... }
    dev.wdogres = fake_pic_wdogres  # DML: connect wdogres { ... }
    
    # Instantiate
    simics.SIM_add_configuration([dev, clk, mem, fake_pic_wdogint, fake_pic_wdogres], None)
    
    return (simics.SIM_get_object(dev.name), simics.SIM_get_object(fake_pic_wdogint.name), simics.SIM_get_object(fake_pic_wdogres.name))
